//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booklet
    {
        public int BookletId { get; set; }
        public string CivilRegistry { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string FamilyNumber { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public string IssuePlace { get; set; }
        public string Number { get; set; }
        public string RegistrationNumber { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
