//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactInfo
    {
        public int ContactInfoId { get; set; }
        public string Address { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string NearKindr { get; set; }
        public string NearPoint { get; set; }
        public string Note { get; set; }
        public string Phone { get; set; }
        public string RelativeRelation { get; set; }
        public string WorkAddress { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
