//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Absences = new HashSet<Absence>();
            this.AdvancePayments = new HashSet<AdvancePayment>();
            this.Booklets = new HashSet<Booklet>();
            this.Coaches = new HashSet<Coach>();
            this.ContactInfos = new HashSet<ContactInfo>();
            this.Documents = new HashSet<Document>();
            this.EmployeePremiums = new HashSet<EmployeePremium>();
            this.EndServiceses = new HashSet<EndServices>();
            this.Evaluations = new HashSet<Evaluation>();
            this.Extraworks = new HashSet<Extrawork>();
            this.IdentificationCards = new HashSet<IdentificationCard>();
            this.JobInfos = new HashSet<JobInfo>();
            this.MilitaryDatas = new HashSet<MilitaryData>();
            this.Passports = new HashSet<Passport>();
            this.Qualifications = new HashSet<Qualification>();
            this.Rewards = new HashSet<Reward>();
            this.Salaries = new HashSet<Salary>();
            this.SalaryInfos = new HashSet<SalaryInfo>();
            this.Sanctions = new HashSet<Sanction>();
            this.SelfCourses = new HashSet<SelfCours>();
            this.SituationResolveJobs = new HashSet<SituationResolveJob>();
            this.TrainingDetails = new HashSet<TrainingDetail>();
            this.Transfers = new HashSet<Transfer>();
            this.Vacations = new HashSet<Vacation>();
        }
    
        public int EmployeeId { get; set; }
        public string Address { get; set; }
        public Nullable<int> AdjectiveEmployeeId { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string BirthPlace { get; set; }
        public int BloodType { get; set; }
        public Nullable<int> ChildernCount { get; set; }
        public string Email { get; set; }
        public string EnglishFatherName { get; set; }
        public string EnglishFirstName { get; set; }
        public string EnglishGrandfatherName { get; set; }
        public string EnglishLastName { get; set; }
        public string FatherName { get; set; }
        public string FirstName { get; set; }
        public int Gender { get; set; }
        public string GrandfatherName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> JobId { get; set; }
        public string LastName { get; set; }
        public string MotherName { get; set; }
        public string NationalNumber { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string Phone { get; set; }
        public Nullable<int> PlaceId { get; set; }
        public int Religion { get; set; }
        public int SocialStatus { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public int C_CreatedBy { get; set; }
        public System.DateTime C_DateCreated { get; set; }
        public System.DateTime C_DateModified { get; set; }
        public int C_ModifiedBy { get; set; }
        public int LibyanOrForeigner { get; set; }
        public Nullable<int> ExactSpecialtyId { get; set; }
        public Nullable<int> WifeNationalityId { get; set; }
        public byte[] Image { get; set; }
        public Nullable<int> ClassificationOnWorkId { get; set; }
        public Nullable<int> ClassificationOnSearchingId { get; set; }
        public string BookFamilySourceNumber { get; set; }
        public string NationaltyMother { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Absence> Absences { get; set; }
        public virtual AdjectiveEmployee AdjectiveEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdvancePayment> AdvancePayments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booklet> Booklets { get; set; }
        public virtual ClassificationOnSearching ClassificationOnSearching { get; set; }
        public virtual ClassificationOnWork ClassificationOnWork { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coach> Coaches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactInfo> ContactInfos { get; set; }
        public virtual Division Division { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Document> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePremium> EmployeePremiums { get; set; }
        public virtual ExactSpecialty ExactSpecialty { get; set; }
        public virtual Job Job { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Nationality Nationality1 { get; set; }
        public virtual Place Place { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EndServices> EndServiceses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evaluation> Evaluations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Extrawork> Extraworks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IdentificationCard> IdentificationCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobInfo> JobInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MilitaryData> MilitaryDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Passport> Passports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qualification> Qualifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reward> Rewards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Salary> Salaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SalaryInfo> SalaryInfos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sanction> Sanctions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SelfCours> SelfCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SituationResolveJob> SituationResolveJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingDetail> TrainingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transfer> Transfers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vacation> Vacations { get; set; }
    }
}
