//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentValue
    {
        public int EmploymentValuesId { get; set; }
        public Nullable<System.DateTime> BenefitFromServicesDate { get; set; }
        public string BenefitFromServicesSide { get; set; }
        public Nullable<System.DateTime> CollaboratorDate { get; set; }
        public string CollaboratorSide { get; set; }
        public Nullable<System.DateTime> ContractDateFrom { get; set; }
        public Nullable<System.DateTime> ContractDateTo { get; set; }
        public Nullable<System.DateTime> DelegationDate { get; set; }
        public string DelegationSide { get; set; }
        public string DesignationIssue { get; set; }
        public Nullable<System.DateTime> DesignationResolutionDate { get; set; }
        public string DesignationResolutionNumber { get; set; }
        public Nullable<System.DateTime> EmptiedDate { get; set; }
        public string EmptiedSide { get; set; }
        public Nullable<int> JobInfoId { get; set; }
        public Nullable<System.DateTime> LoaningDate { get; set; }
        public string LoaningSide { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
        public string TransferSide { get; set; }
    
        public virtual JobInfo JobInfo { get; set; }
    }
}
