//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorySubsended
    {
        public int HistorySubsendedID { get; set; }
        public string DateSubsended { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string HistorySubsendedNote { get; set; }
        public bool ISSubsended { get; set; }
        public bool IsClose { get; set; }
        public string JoubNumber { get; set; }
        public decimal NetSalray { get; set; }
        public string SalaryID { get; set; }
        public string iSCloseMessage { get; set; }
        public string MonthDate { get; set; }
        public bool IsClipord { get; set; }
        public int AbsenceDays { get; set; }
        public decimal FinalSalary { get; set; }
        public decimal SocialSecurityFundBondNumber { get; set; }
        public decimal SolidarityFundBondNumber { get; set; }
        public decimal Total { get; set; }
        public decimal employeSharea { get; set; }
        public decimal jihad { get; set; }
        public decimal subject { get; set; }
        public decimal Absence { get; set; }
    }
}
