//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlmotkamlHrEntities1 : DbContext
    {
        public AlmotkamlHrEntities1()
            : base("name=AlmotkamlHrEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Absence> Absences { get; set; }
        public virtual DbSet<Activity> Activities { get; set; }
        public virtual DbSet<AdjectiveEmployee> AdjectiveEmployees { get; set; }
        public virtual DbSet<AdjectiveEmployeeType> AdjectiveEmployeeTypes { get; set; }
        public virtual DbSet<AdvancePayment> AdvancePayments { get; set; }
        public virtual DbSet<BankBranch> BankBranches { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<Booklet> Booklets { get; set; }
        public virtual DbSet<Branch> Branchs { get; set; }
        public virtual DbSet<Center> Centers { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<ClassificationOnSearching> ClassificationOnSearchings { get; set; }
        public virtual DbSet<ClassificationOnWork> ClassificationOnWorks { get; set; }
        public virtual DbSet<Coach> Coaches { get; set; }
        public virtual DbSet<ContactInfo> ContactInfos { get; set; }
        public virtual DbSet<Corporation> Corporations { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<CurrentSituation> CurrentSituations { get; set; }
        public virtual DbSet<Delegation> Delegations { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DevelopmentState> DevelopmentStates { get; set; }
        public virtual DbSet<DevelopmentTypeA> DevelopmentTypeAs { get; set; }
        public virtual DbSet<DevelopmentTypeB> DevelopmentTypeBs { get; set; }
        public virtual DbSet<DevelopmentTypeC> DevelopmentTypeCs { get; set; }
        public virtual DbSet<DevelopmentTypeD> DevelopmentTypeDs { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<DocumentImage> DocumentImages { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<EmployeePremium> EmployeePremiums { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmploymentValue> EmploymentValues { get; set; }
        public virtual DbSet<EndServices> EndServiceses { get; set; }
        public virtual DbSet<Evaluation> Evaluations { get; set; }
        public virtual DbSet<ExactSpecialty> ExactSpecialties { get; set; }
        public virtual DbSet<Extrawork> Extraworks { get; set; }
        public virtual DbSet<HistorySubsended> HistorySubsendeds { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<IdentificationCard> IdentificationCards { get; set; }
        public virtual DbSet<Info> Infoes { get; set; }
        public virtual DbSet<JobInfo> JobInfos { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<MilitaryData> MilitaryDatas { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Passport> Passports { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<Premium> Premiums { get; set; }
        public virtual DbSet<Qualification> Qualifications { get; set; }
        public virtual DbSet<QualificationType> QualificationTypes { get; set; }
        public virtual DbSet<RequestedQualification> RequestedQualifications { get; set; }
        public virtual DbSet<Reward> Rewards { get; set; }
        public virtual DbSet<RewardType> RewardTypes { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<SalaryCertified> SalaryCertifieds { get; set; }
        public virtual DbSet<SalaryInfo> SalaryInfos { get; set; }
        public virtual DbSet<SalaryPremium> SalaryPremiums { get; set; }
        public virtual DbSet<SalaryUnit> SalaryUnits { get; set; }
        public virtual DbSet<Sanction> Sanctions { get; set; }
        public virtual DbSet<SanctionType> SanctionTypes { get; set; }
        public virtual DbSet<SelfCours> SelfCourses { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<SituationResolveJob> SituationResolveJobs { get; set; }
        public virtual DbSet<Specialty> Specialties { get; set; }
        public virtual DbSet<Staffing> Staffings { get; set; }
        public virtual DbSet<StaffingType> StaffingTypes { get; set; }
        public virtual DbSet<SubSpecialty> SubSpecialties { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TemporaryPremium> TemporaryPremiums { get; set; }
        public virtual DbSet<TrainingDetail> TrainingDetails { get; set; }
        public virtual DbSet<Training> Trainings { get; set; }
        public virtual DbSet<Transfer> Transfers { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vacation> Vacations { get; set; }
        public virtual DbSet<VacationType> VacationTypes { get; set; }
    }
}
