//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class MilitaryData
    {
        public int MilitaryDataId { get; set; }
        public int AdjectiveMilitary { get; set; }
        public string College { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<System.DateTime> GranduationDate { get; set; }
        public string MilitaryNumber { get; set; }
        public string MotherUnit { get; set; }
        public string Rank { get; set; }
        public string Subunit { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
