//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualification
    {
        public int QualificationId { get; set; }
        public System.DateTime Date { get; set; }
        public int EmployeeId { get; set; }
        public string GraduationCountry { get; set; }
        public string NameDonorFoundation { get; set; }
        public int QualificationTypeId { get; set; }
        public Nullable<int> ExactSpecialtyId { get; set; }
        public int C_CreatedBy { get; set; }
        public System.DateTime C_DateCreated { get; set; }
        public System.DateTime C_DateModified { get; set; }
        public int C_ModifiedBy { get; set; }
        public string AquiredSpecialty { get; set; }
        public int DonorFoundationType { get; set; }
        public int Grade { get; set; }
        public Nullable<int> SpecialtyId { get; set; }
        public Nullable<int> SubSpecialtyId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ExactSpecialty ExactSpecialty { get; set; }
        public virtual QualificationType QualificationType { get; set; }
        public virtual Specialty Specialty { get; set; }
        public virtual SubSpecialty SubSpecialty { get; set; }
    }
}
