//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryInfo
    {
        public int SalaryInfoId { get; set; }
        public int BankBranchId { get; set; }
        public decimal BasicSalary { get; set; }
        public string BondNumber { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string FinancialNumber { get; set; }
        public int GuaranteeType { get; set; }
        public string SecurityNumber { get; set; }
        public decimal ExtraValue { get; set; }
        public string FileNumber { get; set; }
        public decimal ExtraGeneralValue { get; set; }
        public int SafeType { get; set; }
        public string NameSecutry { get; set; }
    
        public virtual BankBranch BankBranch { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
