//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryCertified
    {
        public int SalaryCertifiedID { get; set; }
        public int BankBranchId { get; set; }
        public int CheckNumber { get; set; }
        public string Total { get; set; }
    }
}
