//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryUnit
    {
        public int SalaryUnitId { get; set; }
        public decimal BeginningValue { get; set; }
        public int Degree { get; set; }
        public decimal PremiumValue { get; set; }
        public int SalayClassification { get; set; }
        public int C_CreatedBy { get; set; }
        public System.DateTime C_DateCreated { get; set; }
        public System.DateTime C_DateModified { get; set; }
        public int C_ModifiedBy { get; set; }
        public decimal ExtraGeneralValue { get; set; }
        public decimal ExtraValue { get; set; }
    }
}
