//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class SelfCours
    {
        public int SelfCoursesId { get; set; }
        public string CourseName { get; set; }
        public System.DateTime Date { get; set; }
        public string Duration { get; set; }
        public int EmployeeId { get; set; }
        public int Place { get; set; }
        public string Result { get; set; }
        public int SubSpecialtyId { get; set; }
        public string TrainingCenter { get; set; }
        public int C_CreatedBy { get; set; }
        public System.DateTime C_DateCreated { get; set; }
        public System.DateTime C_DateModified { get; set; }
        public int C_ModifiedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual SubSpecialty SubSpecialty { get; set; }
    }
}
