//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Linq
{
    using System;
    using System.Collections.Generic;
    
    public partial class SituationResolveJob
    {
        public int SituationResolveJobId { get; set; }
        public Nullable<int> Boun { get; set; }
        public int BounNow { get; set; }
        public Nullable<System.DateTime> DateDegreeLast { get; set; }
        public System.DateTime DecisionDate { get; set; }
        public string DecisionNumber { get; set; }
        public Nullable<int> Degree { get; set; }
        public int DegreeNow { get; set; }
        public int EmployeeId { get; set; }
        public int C_CreatedBy { get; set; }
        public System.DateTime C_DateCreated { get; set; }
        public System.DateTime C_DateModified { get; set; }
        public int C_ModifiedBy { get; set; }
        public Nullable<System.DateTime> DateBounLast { get; set; }
        public Nullable<int> JobLastId { get; set; }
        public Nullable<int> JobNowId { get; set; }
        public string Note { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Job Job { get; set; }
        public virtual Job Job1 { get; set; }
    }
}
