//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Almotkaml.ArtificialLimbs.Core.Resources.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة تفاصيل قياس(حالات بتر).
        /// </summary>
        public static string AmputationDetails_Create {
            get {
                return ResourceManager.GetString("AmputationDetails_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف تفاصيل قياس(حالات بتر).
        /// </summary>
        public static string AmputationDetails_Delete {
            get {
                return ResourceManager.GetString("AmputationDetails_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل تفاصيل قياس(حالات بتر).
        /// </summary>
        public static string AmputationDetails_Edit {
            get {
                return ResourceManager.GetString("AmputationDetails_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة سجل إلى حالات البتر.
        /// </summary>
        public static string AmputationStatues_Create {
            get {
                return ResourceManager.GetString("AmputationStatues_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف سجل من حالات البتر.
        /// </summary>
        public static string AmputationStatues_Delet {
            get {
                return ResourceManager.GetString("AmputationStatues_Delet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل سجل من حالات البتر.
        /// </summary>
        public static string AmputationStatues_Edit {
            get {
                return ResourceManager.GetString("AmputationStatues_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر إلى قائمة أنواع البتر.
        /// </summary>
        public static string AmputationTypes_Create {
            get {
                return ResourceManager.GetString("AmputationTypes_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر من قائمة أنواع البتر.
        /// </summary>
        public static string AmputationTypes_Delete {
            get {
                return ResourceManager.GetString("AmputationTypes_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر من قائمة أنواع البتر.
        /// </summary>
        public static string AmputationTypes_Edit {
            get {
                return ResourceManager.GetString("AmputationTypes_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة موعد كشف.
        /// </summary>
        public static string Appointment_Create {
            get {
                return ResourceManager.GetString("Appointment_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف موعد كشف.
        /// </summary>
        public static string Appointment_Delete {
            get {
                return ResourceManager.GetString("Appointment_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل موعد كشف.
        /// </summary>
        public static string Appointment_Edit {
            get {
                return ResourceManager.GetString("Appointment_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإجراء النسخ الاحتياطي.
        /// </summary>
        public static string BackUp_Create {
            get {
                return ResourceManager.GetString("BackUp_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة فرع بلدي جديد.
        /// </summary>
        public static string Branch_Create {
            get {
                return ResourceManager.GetString("Branch_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف فرع بلدي.
        /// </summary>
        public static string Branch_Delete {
            get {
                return ResourceManager.GetString("Branch_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل فرع بلدي.
        /// </summary>
        public static string Branch_Edit {
            get {
                return ResourceManager.GetString("Branch_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر في قائمة المدن.
        /// </summary>
        public static string Cities_Create {
            get {
                return ResourceManager.GetString("Cities_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر في قائمة المدن.
        /// </summary>
        public static string Cities_Delete {
            get {
                return ResourceManager.GetString("Cities_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة المدن.
        /// </summary>
        public static string Cities_Edit {
            get {
                return ResourceManager.GetString("Cities_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتحديث بيانات الشركة.
        /// </summary>
        public static string CompanyInfo_Edit {
            get {
                return ResourceManager.GetString("CompanyInfo_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة نوع تعاقد.
        /// </summary>
        public static string ContractType_Create {
            get {
                return ResourceManager.GetString("ContractType_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف نوع تعاقد.
        /// </summary>
        public static string ContractType_Delete {
            get {
                return ResourceManager.GetString("ContractType_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر في قائمة البلدان.
        /// </summary>
        public static string Countries_Create {
            get {
                return ResourceManager.GetString("Countries_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر في قائمة البلدان.
        /// </summary>
        public static string Countries_Delete {
            get {
                return ResourceManager.GetString("Countries_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة البلدان.
        /// </summary>
        public static string Countries_Edit {
            get {
                return ResourceManager.GetString("Countries_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة تفاصيل قياس(حالات يومية).
        /// </summary>
        public static string DailyDetailes_Create {
            get {
                return ResourceManager.GetString("DailyDetailes_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف تفاصيل قياس(حالات يومية).
        /// </summary>
        public static string DailyDetailes_Delete {
            get {
                return ResourceManager.GetString("DailyDetailes_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل تفاصيل قياس(حالات يومية).
        /// </summary>
        public static string DailyDetailes_Edit {
            get {
                return ResourceManager.GetString("DailyDetailes_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة سجل إلى قائمة الحالات اليومية.
        /// </summary>
        public static string DailyStatues_Create {
            get {
                return ResourceManager.GetString("DailyStatues_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف سجل في قائمة الحالات اليومية.
        /// </summary>
        public static string DailyStatues_Delete {
            get {
                return ResourceManager.GetString("DailyStatues_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل سجل في قائمة الحالات اليومية.
        /// </summary>
        public static string DailyStatues_Edit {
            get {
                return ResourceManager.GetString("DailyStatues_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة قسم.
        /// </summary>
        public static string Department_Create {
            get {
                return ResourceManager.GetString("Department_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر في قائمة الأقسام.
        /// </summary>
        public static string Department_Delete {
            get {
                return ResourceManager.GetString("Department_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة الأقسام.
        /// </summary>
        public static string Department_Edit {
            get {
                return ResourceManager.GetString("Department_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر إلى قائمة الأجهزة/الأطراف التعويضية.
        /// </summary>
        public static string Device_Create {
            get {
                return ResourceManager.GetString("Device_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر في قائمة  الأجهزة/الأطراف التعويضية.
        /// </summary>
        public static string Device_Delete {
            get {
                return ResourceManager.GetString("Device_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة  الأجهزة/الأطراف التعويضية.
        /// </summary>
        public static string Device_Edit {
            get {
                return ResourceManager.GetString("Device_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر إلى قائمة مواعيد الأطباء.
        /// </summary>
        public static string DoctorShift_Create {
            get {
                return ResourceManager.GetString("DoctorShift_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر إلى قائمة مواعيد الأطباء.
        /// </summary>
        public static string DoctorShift_Delete {
            get {
                return ResourceManager.GetString("DoctorShift_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر إلى قائمة مواعيد الأطباء.
        /// </summary>
        public static string DoctorShift_Edit {
            get {
                return ResourceManager.GetString("DoctorShift_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بانشاء تقرير حر.
        /// </summary>
        public static string DynamicReport_Create {
            get {
                return ResourceManager.GetString("DynamicReport_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة موظف جديد.
        /// </summary>
        public static string Employee_Create {
            get {
                return ResourceManager.GetString("Employee_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف موظف.
        /// </summary>
        public static string Employee_Delete {
            get {
                return ResourceManager.GetString("Employee_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل موظف.
        /// </summary>
        public static string Employee_Edit {
            get {
                return ResourceManager.GetString("Employee_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة سجل في قائمة العطل الرسمية.
        /// </summary>
        public static string Holiday_Create {
            get {
                return ResourceManager.GetString("Holiday_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف سجل في قائمة العطل الرسمية.
        /// </summary>
        public static string Holiday_Delete {
            get {
                return ResourceManager.GetString("Holiday_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل سجل في قائمة العطل الرسمية.
        /// </summary>
        public static string Holiday_Edit {
            get {
                return ResourceManager.GetString("Holiday_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر إلى قائمة الجهات.
        /// </summary>
        public static string Hospitals_Create {
            get {
                return ResourceManager.GetString("Hospitals_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر إلى قائمة الجهات.
        /// </summary>
        public static string Hospitals_Delete {
            get {
                return ResourceManager.GetString("Hospitals_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر إلى قائمة الجهات.
        /// </summary>
        public static string Hospitals_Edit {
            get {
                return ResourceManager.GetString("Hospitals_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر إلى قائمة العلاجات.
        /// </summary>
        public static string Medicine_Create {
            get {
                return ResourceManager.GetString("Medicine_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر إلى قائمة العلاجات.
        /// </summary>
        public static string Medicine_Delete {
            get {
                return ResourceManager.GetString("Medicine_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة العلاجات.
        /// </summary>
        public static string Medicine_Edit {
            get {
                return ResourceManager.GetString("Medicine_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة عنصر إلى قائمة الجنسيات.
        /// </summary>
        public static string Nationality_Create {
            get {
                return ResourceManager.GetString("Nationality_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف عنصر من قائمة الجنسيات.
        /// </summary>
        public static string Nationality_Delete {
            get {
                return ResourceManager.GetString("Nationality_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل عنصر في قائمة الجنسيات.
        /// </summary>
        public static string Nationality_Edit {
            get {
                return ResourceManager.GetString("Nationality_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة سجل مريض.
        /// </summary>
        public static string Patient_Create {
            get {
                return ResourceManager.GetString("Patient_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف سجل مريض.
        /// </summary>
        public static string Patient_Delete {
            get {
                return ResourceManager.GetString("Patient_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل بيانات سجل مريض.
        /// </summary>
        public static string Patient_Edit {
            get {
                return ResourceManager.GetString("Patient_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة محلة.
        /// </summary>
        public static string Place_Create {
            get {
                return ResourceManager.GetString("Place_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف محلة.
        /// </summary>
        public static string Place_Delete {
            get {
                return ResourceManager.GetString("Place_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل محلة.
        /// </summary>
        public static string Place_Edit {
            get {
                return ResourceManager.GetString("Place_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتحديث إعدادات المنظومة.
        /// </summary>
        public static string Setting_Edit {
            get {
                return ResourceManager.GetString("Setting_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة موعد علاج.
        /// </summary>
        public static string TreatmentAppointment_Create {
            get {
                return ResourceManager.GetString("TreatmentAppointment_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة موعد علاج.
        /// </summary>
        public static string TreatmentAppointment_Delete {
            get {
                return ResourceManager.GetString("TreatmentAppointment_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة موعد علاج.
        /// </summary>
        public static string TreatmentAppointment_Edit {
            get {
                return ResourceManager.GetString("TreatmentAppointment_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة جلسة علاج.
        /// </summary>
        public static string TreatmentSessions_Create {
            get {
                return ResourceManager.GetString("TreatmentSessions_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة جلسة علاج.
        /// </summary>
        public static string TreatmentSessions_Delete {
            get {
                return ResourceManager.GetString("TreatmentSessions_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة جلسة علاج.
        /// </summary>
        public static string TreatmentSessions_Edit {
            get {
                return ResourceManager.GetString("TreatmentSessions_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة مستخدم جديد.
        /// </summary>
        public static string User_Create {
            get {
                return ResourceManager.GetString("User_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف مستخدم.
        /// </summary>
        public static string User_Delete {
            get {
                return ResourceManager.GetString("User_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل مستخدم.
        /// </summary>
        public static string User_Edit {
            get {
                return ResourceManager.GetString("User_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بإضافة مجموعة صلاحيات جديدة.
        /// </summary>
        public static string UserGroup_Create {
            get {
                return ResourceManager.GetString("UserGroup_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بحذف مجموعة صلاحيات مستخدمين.
        /// </summary>
        public static string UserGroup_Delete {
            get {
                return ResourceManager.GetString("UserGroup_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قام بتعديل صلاحيات مستخدمين.
        /// </summary>
        public static string UserGroup_Edit {
            get {
                return ResourceManager.GetString("UserGroup_Edit", resourceCulture);
            }
        }
    }
}
