//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Almotkaml.ArtificialLimbs.Core.Resources.SharedMessages", typeof(SharedMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان تكون الخيارات على الاقل ستة خيارات.
        /// </summary>
        public static string CheckBoxNumber {
            get {
                return ResourceManager.GetString("CheckBoxNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك حذف هذا السجل ,
        /// </summary>
        public static string UnableToDelete
        {
            get
            {
                return ResourceManager.GetString("UnableToDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا تكون الخيارات  اكثر  من ثمانية خيارات.
        /// </summary>
        public static string CheckBoxNumber2 {
            get {
                return ResourceManager.GetString("CheckBoxNumber2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لاتتجاوز عدد ايام الإجازة الطارئة عن تلاثة ايام متتالية.
        /// </summary>
        public static string conditionvacationemergency {
            get {
                return ResourceManager.GetString("conditionvacationemergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لاتزيد عدد ايام اجازة الابوة عن يومين .
        /// </summary>
        public static string conditionvacationpaternityLeave {
            get {
                return ResourceManager.GetString("conditionvacationpaternityLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لاتزيد عدد ايام الإجازة المرضية عن 45 يوم متتالية.
        /// </summary>
        public static string conditionvacationsick {
            get {
                return ResourceManager.GetString("conditionvacationsick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الموظف لديه هذه الاجازة بالفعل.
        /// </summary>
        public static string existvacation {
            get {
                return ResourceManager.GetString("existvacation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التاريخ الذي قمت بإدخاله غير صحيح ..
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد لديك خطأ في إدخال إحدى التواريخ ..
        /// </summary>
        public static string InvalidDateRange {
            get {
                return ResourceManager.GetString("InvalidDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال رقم صحيح في حقل {0} قبل المتابعة ..
        /// </summary>
        public static string InvalidNumber {
            get {
                return ResourceManager.GetString("InvalidNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال تاريخ قديم في حقل {0} ..
        /// </summary>
        public static string InvalidPastDate {
            get {
                return ResourceManager.GetString("InvalidPastDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال قيمة صحيحة لحقل {0} قبل المتابعة ..
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال {0} قبل المتابعة ..
        /// </summary>
        public static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لقد وصلت للحد الأعلى من السجلات الممكن إضافتها في النسخة التجريبية , عدد السجلات الأقصى المسموح به = .
        /// </summary>
        public static string LimitExceeded {
            get {
                return ResourceManager.GetString("LimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم أو كلمة المرور المدخلة غير صحيحة ..
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لا تزيد عدد ايام الإجازة عن 14 يوم.
        /// </summary>
        public static string marriageleave {
            get {
                return ResourceManager.GetString("marriageleave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكنك إدخال أكثر من {0} حرفاً في حقل {1} ..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب التأكد من الرقم الوطني {1} ..
        /// </summary>
        public static string NationalityNumber
        {
            get
            {
                return ResourceManager.GetString("NationalityNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب التأكد من الرقم الوطني {1} ..
        /// </summary>
        public static string PhoneNumber
        {
            get
            {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to الاسم الذي أدخلته موجود مسبقاً ..
        /// </summary>
        public static string NameExisted {
            get {
                return ResourceManager.GetString("NameExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب التأكد من الرقم الوطني.
        /// </summary>
       
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد.
        /// </summary>
        public static string NotExisted {
            get {
                return ResourceManager.GetString("NotExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور التي أدخلتها غير متطابقة ..
        /// </summary>
        public static string PasswordNotMatch {
            get {
                return ResourceManager.GetString("PasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب اختيار {0} قبل المتابعة ..
        /// </summary>
        public static string ShouldSelected {
            get {
                return ResourceManager.GetString("ShouldSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب الاختيار من القائمة قبل المتابعة ..
        /// </summary>
        public static string ShouldSelectFromList {
            get {
                return ResourceManager.GetString("ShouldSelectFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت الإضافة بنجاح ..
        /// </summary>
        public static string SuccessCreate {
            get {
                return ResourceManager.GetString("SuccessCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحذف بنجاح ..
        /// </summary>
        public static string SuccessDelete {
            get {
                return ResourceManager.GetString("SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم التعديل بنجاح ..
        /// </summary>
        public static string SuccessEdit {
            get {
                return ResourceManager.GetString("SuccessEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن إدخال قيمة أقل من صفر في حقل {0} ..
        /// </summary>
        public static string TrueOrZero {
            get {
                return ResourceManager.GetString("TrueOrZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال رقم سنة صحيح في حقل {0} ..
        /// </summary>
        public static string TrueYear {
            get {
                return ResourceManager.GetString("TrueYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم الذي أدخلته موجود مسبقا ..
        /// </summary>
        public static string UserExisted {
            get {
                return ResourceManager.GetString("UserExisted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايوجد رصيد اجازة طارئة لهذا الموظف.
        /// </summary>
        public static string vacationemergency {
            get {
                return ResourceManager.GetString("vacationemergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لايوجد رصيد اجازة  مرضية لهذا الموظف.
        /// </summary>
        public static string vacationsick {
            get {
                return ResourceManager.GetString("vacationsick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ان لاتزيد عدد ايام الإجازة عن 20 يوم.
        /// </summary>
        public static string yearHauj {
            get {
                return ResourceManager.GetString("yearHauj", resourceCulture);
            }
        }

    }
}
