//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Almotkaml.ArtificialLimbs.Core.Resources.titles", typeof(titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السكن.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العمر (فوق/تحت).
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بتر.
        /// </summary>
        public static string Amputation {
            get {
                return ResourceManager.GetString("Amputation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البتر.
        /// </summary>
        public static string AmputationDate {
            get {
                return ResourceManager.GetString("AmputationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع البتر.
        /// </summary>
        public static string AmputationName {
            get {
                return ResourceManager.GetString("AmputationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جهة البتر.
        /// </summary>
        public static string AmputationPart {
            get {
                return ResourceManager.GetString("AmputationPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبب البتر.
        /// </summary>
        public static string AmputationReason {
            get {
                return ResourceManager.GetString("AmputationReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم العربي.
        /// </summary>
        public static string ArabicName {
            get {
                return ResourceManager.GetString("ArabicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم العربي.
        /// </summary>
        public static string ArbicName {
            get {
                return ResourceManager.GetString("ArbicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مساعد الفني.
        /// </summary>
        public static string Assistant {
            get {
                return ResourceManager.GetString("Assistant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع البلدي.
        /// </summary>
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المدينة.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البلد.
        /// </summary>
        public static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يومية.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من تاريخ.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الى تاريخ.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القسم.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الجهاز.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفني.
        /// </summary>
        public static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنثى.
        /// </summary>
        public static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إناث.
        /// </summary>
        public static string females {
            get {
                return ResourceManager.GetString("females", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التجربة الاولى.
        /// </summary>
        public static string FirstTestDate {
            get {
                return ResourceManager.GetString("FirstTestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القدم.
        /// </summary>
        public static string Foot {
            get {
                return ResourceManager.GetString("Foot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعة.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة القادم منها.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المشفى.
        /// </summary>
        public static string HospitalName {
            get {
                return ResourceManager.GetString("HospitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعة.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أطفال.
        /// </summary>
        public static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرجل.
        /// </summary>
        public static string leg {
            get {
                return ResourceManager.GetString("leg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليسرى LT.
        /// </summary>
        public static string LT {
            get {
                return ResourceManager.GetString("LT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        public static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكور.
        /// </summary>
        public static string males {
            get {
                return ResourceManager.GetString("males", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجال.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ القياس.
        /// </summary>
        public static string MeasurementDate {
            get {
                return ResourceManager.GetString("MeasurementDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاثنين.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الوطني.
        /// </summary>
        public static string NationalityNumber {
            get {
                return ResourceManager.GetString("NationalityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة.
        /// </summary>
        public static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القياس.
        /// </summary>
        public static string PartMeasure {
            get {
                return ResourceManager.GetString("PartMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم المنطقة.
        /// </summary>
        public static string PartNO {
            get {
                return ResourceManager.GetString("PartNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المريض.
        /// </summary>
        public static string PatientId {
            get {
                return ResourceManager.GetString("PatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المريض.
        /// </summary>
        public static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        public static string PhoneNO {
            get {
                return ResourceManager.GetString("PhoneNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحلة.
        /// </summary>
        public static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الاستلام.
        /// </summary>
        public static string ReceiptDate {
            get {
                return ResourceManager.GetString("ReceiptDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الإشاري.
        /// </summary>
        public static string ReferenceNo {
            get {
                return ResourceManager.GetString("ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التسجيل.
        /// </summary>
        public static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من تاريخ التسجيل.
        /// </summary>
        public static string RegistrationDateFrom {
            get {
                return ResourceManager.GetString("RegistrationDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إلى تاريخ التسجيل.
        /// </summary>
        public static string RegistrationDateTo {
            get {
                return ResourceManager.GetString("RegistrationDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اليمنى RT.
        /// </summary>
        public static string RT {
            get {
                return ResourceManager.GetString("RT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التجربة الثاتية.
        /// </summary>
        public static string SecondTestDate {
            get {
                return ResourceManager.GetString("SecondTestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحذاء.
        /// </summary>
        public static string ShoeNO {
            get {
                return ResourceManager.GetString("ShoeNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باطن القدم.
        /// </summary>
        public static string sole {
            get {
                return ResourceManager.GetString("sole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموع.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التصنيف.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سنة الميلاد.
        /// </summary>
        public static string YearOfBirth {
            get {
                return ResourceManager.GetString("YearOfBirth", resourceCulture);
            }
        }
    }
}
