//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Almotkaml.ArtificialLimbs.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class titls {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal titls() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Almotkaml.ArtificialLimbs.Core.Resources.titls", typeof(titls).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكل.
        /// </summary>
        internal static string AllEmployee {
            get {
                return ResourceManager.GetString("AllEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكل.
        /// </summary>
        internal static string AllTypes {
            get {
                return ResourceManager.GetString("AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع البتر.
        /// </summary>
        internal static string AmputationName {
            get {
                return ResourceManager.GetString("AmputationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الحجز.
        /// </summary>
        internal static string AppointmentDate {
            get {
                return ResourceManager.GetString("AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحجز.
        /// </summary>
        internal static string AppointmentNumber {
            get {
                return ResourceManager.GetString("AppointmentNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحالة.
        /// </summary>
        internal static string AppointmentState {
            get {
                return ResourceManager.GetString("AppointmentState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم العربي.
        /// </summary>
        internal static string ArbicName {
            get {
                return ResourceManager.GetString("ArbicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الميلاد.
        /// </summary>
        internal static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفرع البلدي.
        /// </summary>
        internal static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المدينة.
        /// </summary>
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم البلد.
        /// </summary>
        internal static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من تاريخ.
        /// </summary>
        internal static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الى تاريخ.
        /// </summary>
        internal static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التشخيص.
        /// </summary>
        internal static string Diagnosis {
            get {
                return ResourceManager.GetString("Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الدكتور.
        /// </summary>
        internal static string DoctorName {
            get {
                return ResourceManager.GetString("DoctorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOSC.
        /// </summary>
        internal static string DOSC {
            get {
                return ResourceManager.GetString("DOSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علاج كهربائي.
        /// </summary>
        internal static string Electro {
            get {
                return ResourceManager.GetString("Electro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدكتور.
        /// </summary>
        internal static string EmployeeId {
            get {
                return ResourceManager.GetString("EmployeeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الموظف.
        /// </summary>
        internal static string EmployeeName {
            get {
                return ResourceManager.GetString("EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        internal static string EnglishName {
            get {
                return ResourceManager.GetString("EnglishName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انثى.
        /// </summary>
        internal static string female {
            get {
                return ResourceManager.GetString("female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الملف.
        /// </summary>
        internal static string FileNumber {
            get {
                return ResourceManager.GetString("FileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45 دقيقة.
        /// </summary>
        internal static string FortyFiveMin {
            get {
                return ResourceManager.GetString("FortyFiveMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجمعة.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة.
        /// </summary>
        internal static string GenderTypes {
            get {
                return ResourceManager.GetString("GenderTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دخل.
        /// </summary>
        internal static string getIn {
            get {
                return ResourceManager.GetString("getIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المجموعة.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 30 دقيقة.
        /// </summary>
        internal static string Half {
            get {
                return ResourceManager.GetString("Half", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المناسبة.
        /// </summary>
        internal static string Holiday {
            get {
                return ResourceManager.GetString("Holiday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجهة القادم منها.
        /// </summary>
        internal static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المشفى.
        /// </summary>
        internal static string HospitalName {
            get {
                return ResourceManager.GetString("HospitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ساعة.
        /// </summary>
        internal static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أطفال.
        /// </summary>
        internal static string Kids {
            get {
                return ResourceManager.GetString("Kids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذكر.
        /// </summary>
        internal static string male {
            get {
                return ResourceManager.GetString("male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رجال.
        /// </summary>
        internal static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العلاج.
        /// </summary>
        internal static string Medicine {
            get {
                return ResourceManager.GetString("Medicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع العلاج.
        /// </summary>
        internal static string MedicineType {
            get {
                return ResourceManager.GetString("MedicineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاثنين.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علاج حركي.
        /// </summary>
        internal static string Motor {
            get {
                return ResourceManager.GetString("Motor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنسية.
        /// </summary>
        internal static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الرقم الوطني.
        /// </summary>
        internal static string NationalityNumber {
            get {
                return ResourceManager.GetString("NationalityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير موجود.
        /// </summary>
        internal static string Notexisting {
            get {
                return ResourceManager.GetString("Notexisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العلاج الطبيعي.
        /// </summary>
        internal static string NTEmployee {
            get {
                return ResourceManager.GetString("NTEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المريض.
        /// </summary>
        internal static string PatientId {
            get {
                return ResourceManager.GetString("PatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المريض.
        /// </summary>
        internal static string PatientName {
            get {
                return ResourceManager.GetString("PatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف.
        /// </summary>
        internal static string PhoneNO {
            get {
                return ResourceManager.GetString("PhoneNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فني العلاج.
        /// </summary>
        internal static string Physio {
            get {
                return ResourceManager.GetString("Physio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المحلة.
        /// </summary>
        internal static string Place {
            get {
                return ResourceManager.GetString("Place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 دقيقة.
        /// </summary>
        internal static string Quarter {
            get {
                return ResourceManager.GetString("Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كشف.
        /// </summary>
        internal static string reservation {
            get {
                return ResourceManager.GetString("reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الكشف.
        /// </summary>
        internal static string reservationType {
            get {
                return ResourceManager.GetString("reservationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجعة.
        /// </summary>
        internal static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السبت.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ جلسة العلاج.
        /// </summary>
        internal static string SessionDate {
            get {
                return ResourceManager.GetString("SessionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الجلسات.
        /// </summary>
        internal static string SessionsCount {
            get {
                return ResourceManager.GetString("SessionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الموعد.
        /// </summary>
        internal static string ShiftDate {
            get {
                return ResourceManager.GetString("ShiftDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأحد.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الثلاثاء.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التوقيت.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ بدء العلاج.
        /// </summary>
        internal static string TreatmentDate {
            get {
                return ResourceManager.GetString("TreatmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ انتهاء العلاج.
        /// </summary>
        internal static string TreatmentEndDate {
            get {
                return ResourceManager.GetString("TreatmentEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدة العلاج.
        /// </summary>
        internal static string TreatmentHours {
            get {
                return ResourceManager.GetString("TreatmentHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صالة.
        /// </summary>
        internal static string TreatmentRoom {
            get {
                return ResourceManager.GetString("TreatmentRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الصالة.
        /// </summary>
        internal static string TreatmentRoomNumber {
            get {
                return ResourceManager.GetString("TreatmentRoomNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الخميس.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتظار.
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإربعاء.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نساء.
        /// </summary>
        internal static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
    }
}
